# Change these first
owner: SteffenGivard # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Steffen Givard
    url: https://steffengivard.dk
  - name: Martin Roos
    url: https://martinroos.dk
  - name: Bjarke Kingo
    url: https://bjarkekingo.dk
  - name: Sportsapp
    url: 64.190.90.48
  - name: Culture Me
    url: https://www.culture-me.dk
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.steffengivard.dk
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Status** of various websites."
  introMessage: This is a status page showing uptime information for various websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
